version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker:
    build: .
    command: python -m app.worker
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
